health:
    path: /health
    controller: App\Controller\Health::index
    methods: [GET]

create-author:
    path: /authors
    controller: App\Controller\AuthorsController::create
    method: [POST]
