health:
    path: /health
    controller: App\Controller\Health::index
    methods: [GET]

create-author:
    path: /authors
    controller: App\Controller\Authors\AuthorsController::create
    methods: [POST]
