# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\Authors\AuthorsController:
        class: App\Controller\Authors\AuthorsController
        arguments:
            - '@App\Application\Author\CreateAuthor'
        tags: ['controller.service_arguments']

    App\Application\Author\CreateAuthor:
        class: App\Application\Author\CreateAuthor
        arguments:
            - '@App\Infrastructure\Model\Author\MySqlAuthorRepository'
            - '@App\Infrastructure\Model\Id\RamseyUuidGenerator'

    App\Application\Author\GetAuthor:
        class: App\Application\Author\GetAuthor
        arguments:
            - '@App\Infrastructure\Model\Author\MySqlAuthorRepository'

    App\Infrastructure\Model\Author\MySqlAuthorRepository:
        class: App\Infrastructure\Model\Author\MySqlAuthorRepository
        arguments:
            - '@db.blog'

    App\Infrastructure\Model\Id\RamseyUuidGenerator:
        class: App\Infrastructure\Model\Id\RamseyUuidGenerator

    db.blog:
        class: Doctrine\DBAL\Connection
        factory: Doctrine\DBAL\DriverManager::getConnection
        arguments:
            $params:
                driver: pdo_mysql
                host: '%env(MYSQL_HOST)%'
                port: ~
                user: '%env(MYSQL_USER)%'
                password: '%env(MYSQL_PASSWORD)%'
                dbname: '%env(MYSQL_DATABASE)%'
                charset: UTF8
