name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: up containers
        run: make up

      - name: install dependencies
        run: make install-dependencies

      - name: run tests
        run: make test
